name: intel-oneapi
description: Build codes using Intel OneAPI components on Github actions
author: 'Dr. Ravindra Shinde'
branding:
  icon: 'code'
  color: 'orange'

inputs:
  basekit:
    description: 'Install Intel OneAPI Base Toolkit'
    required: true
    default: 'true'
  hpckit:
    description: 'Install Intel OneAPI HPC Toolkit and Intel MKL'
    required: true
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Download Intel oneAPI
      if: runner.os == 'Linux'
      id: download
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y gpg-agent wget
        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt update

    - name: Cache Intel oneAPI components
      uses: actions/cache@v4.0.2
      with:
        path: /opt/intel
        key: ${{ runner.os }}-oneapi
        restore-keys: |
          ${{ runner.os }}-oneapi

    - name: Install Intel oneAPI Base Toolkit
      if: inputs.basekit == 'true'
      shell: bash
      run: |
        sudo apt-get install -y intel-basekit
        source /opt/intel/oneapi/setvars.sh

    - name: Install Intel oneAPI HPC Toolkit
      if: inputs.hpckit == 'true'
      shell: bash
      run: |
        sudo apt-get install -y intel-mkl
        sudo apt-get install -y intel-hpckit
        source /opt/intel/oneapi/setvars.sh

    - name: Instal Intel oneAPI Fortran Compiler
      if: inputs.fortran == 'true'
      shell: bash
      run: |
        sudo apt-get install -y intel-oneapi-compiler-fortran
        source /opt/intel/oneapi/setvars.sh

    - name: Install Intel oneAPI C++ Compiler
      if: inputs.cpp == 'true'
      shell: bash
      run: |
        sudo apt-get install -y intel-oneapi-compiler-dpcpp-cpp
        sudo apt-get install -y intel-oneapi-compiler-cpp
        source /opt/intel/oneapi/setvars.sh

    - name: Install Intel oneAPI MPI
      if: inputs.mpi == 'true'
      shell: bash
      run: |
        sudo apt-get install -y intel-oneapi-mpi
        source /opt/intel/oneapi/setvars.sh

    - name: Install Intel MKL Library
      if: inputs.mkl == 'true'
      shell: bash
      run: |
        sudo apt-get install -y intel-oneapi-mkl
        source /opt/intel/oneapi/setvars.sh