name: intel-oneapi
description: Build codes using Intel OneAPI components on Github actions
author: 'Dr. Ravindra Shinde'
branding:
  icon: 'code'
  color: 'orange'

inputs:
  components:
    description: 'Comma-separated list of Intel OneAPI components to install (e.g., fortran, cpp, mpi, mkl, basekit, hpckit)'
    required: true
    default: 'fortran,cpp,mpi,mkl'

runs:
  using: 'composite'
  steps:
    - name: Download Intel oneAPI
      if: runner.os == 'Linux'
      id: download
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y gpg-agent wget
        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt update

    - name: Cache Intel oneAPI components
      uses: actions/cache@v4.0.2
      with:
        path: /opt/intel
        key: ${{ runner.os }}-oneapi
        restore-keys: |
          ${{ runner.os }}-oneapi

    - name: Install Intel oneAPI components
      shell: bash
      run: |
        # Convert comma-separated components into an array
        components_list="${{ inputs.components }}"
        IFS=',' read -ra COMPONENTS <<< "$components_list"

        # Iterate over each component and install accordingly
        for component in "${COMPONENTS[@]}"; do
          case "$component" in
            basekit)
              echo "Installing Intel OneAPI Base Toolkit"
              sudo apt-get install -y intel-basekit
              ;;
            hpckit)
              echo "Installing Intel OneAPI HPC Toolkit"
              sudo apt-get install -y intel-hpckit
              ;;
            fortran)
              echo "Installing Intel OneAPI Fortran Compiler"
              sudo apt-get install -y intel-oneapi-compiler-fortran
              ;;
            cpp)
              echo "Installing Intel OneAPI C++ Compiler"
              sudo apt-get install -y intel-oneapi-compiler-dpcpp-cpp
              ;;
            mpi)
              echo "Installing Intel OneAPI MPI"
              sudo apt-get install -y intel-oneapi-mpi
              ;;
            mkl)
              echo "Installing Intel MKL"
              sudo apt-get install -y intel-oneapi-mkl
              ;;
            *)
              echo "Unknown component: $component"
              ;;
          esac
        done

        # Source the oneAPI environment
        source /opt/intel/oneapi/setvars.sh
