name: intel-oneapi

on:
  pull_request:
    types : [opened, synchronize, reopened]
  push:
    branches:
      - main
jobs:
  build_code:
    name: Build code with Intel OneAPI
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: bash --noprofile --norc {0}
    steps:
      - name: Use Intel oneAPI GitHub Actions fast setup
        uses: neelravi/intel-oneapi-github-actions@latest
        with:
          components: fortran,cpp,mpi,mkl

      - name: Cache Intel oneAPI components
        uses: actions/cache@v4
        with:
          path: /opt/intel
          key: ${{ runner.os }}-oneapi
          restore-keys: |
            ${{ runner.os }}-oneapi

      - name: Checkout sample code
        uses: actions/checkout@v4.1.7

      - name: Compile and run C++ program
        run: |
          source /opt/intel/oneapi/setvars.sh
          icpx -o hello_cpp hello.cpp
          ./hello_cpp

      - name: Compile and run Fortran program
        run: |
          source /opt/intel/oneapi/setvars.sh
          ifx -o hello_fortran hello.f90
          ./hello_fortran

      - name: Compile and run MPI C++ program
        run: |
          source /opt/intel/oneapi/setvars.sh
          mpiicpx -o hello_mpi_cpp hello_mpi.cpp
          mpirun -np 2 ./hello_mpi_cpp

      - name: Compile and run MPI Fortran program
        run: |
          source /opt/intel/oneapi/setvars.sh
          mpiifx -o hello_mpi_fortran hello_mpi.f90
          mpirun -np 2 ./hello_mpi_fortran
