name: intel-oneapi

on:
  pull_request:
    types : [opened, synchronize, reopened]
  push:
    branches:
      - main
jobs:
  build_code:
    name: Build code with Intel OneAPI
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: bash --noprofile --norc {0}
    steps:
      - name: Download Intel oneAPI
        run: |
          sudo apt update
          sudo apt install -y gpg-agent wget
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt update

      - name: Cache Intel oneAPI components
        uses: actions/cache@v2
        with:
          path: /opt/intel
          key: ${{ runner.os }}-oneapi
          restore-keys: |
            ${{ runner.os }}-oneapi

      - name: install Intel oneapi components
        run: |
          sudo apt-get install -y intel-basekit
          sudo apt-get install -y intel-hpckit

      - name: Checkout sample code
        uses: actions/checkout@v4

      - name: Compile and run C++ program
        run: |
          source /opt/intel/oneapi/setvars.sh
          icpx -o hello_cpp hello.cpp
          ./hello_cpp

      - name: Compile and run Fortran program
        run: |
          source /opt/intel/oneapi/setvars.sh
          ifx -o hello_fortran hello.f90
          ./hello_fortran

      - name: Compile and run MPI C++ program
        run: |
          source /opt/intel/oneapi/setvars.sh
          mpiicpx -o hello_mpi_cpp hello_mpi.cpp
          mpirun -np 2 ./hello_mpi_cpp

      - name: Compile and run MPI Fortran program
        run: |
          source /opt/intel/oneapi/setvars.sh
          mpiifx -o hello_mpi_fortran hello_mpi.f90
          mpirun -np 2 ./hello_mpi_fortran
